name: Deploy to Azure

on: [push]

env:
  AZURE_WEBAPP_NAME: anuswbot
  AZURE_WEBAPP_PACKAGE_PATH: "anu-sw-slackbot"
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - run: ls -la

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@main
      with:
        node-version: ${{ env.NODE_VERSION }}

    - run: ls -la

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    
    - run: ls -la
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}