name: Deploy to App Engine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: 'ubuntu-latest'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v2'
    
    - name: 'Generate .env file'
      run: |
        echo "SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL" >> .env
        echo "MONGODB_URI=$MONGODB_URI >> .env"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: app.yaml

    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
